---
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  restartPolicy: OnFailure
  containers:
    - image: centos:7
      name: pod-example-ctr
      command: ["sleep"]
      args: ["100000"]
      resources:
        limits:
          b-com.com/accelerator: 1
